language: go
sudo: false
go:
  - "1.10"
before_install:
  - go get -u github.com/golang/dep/cmd/dep
install:
  - "$GOPATH/bin/dep ensure"
env:
  global:
    - NAME=clash
    - BINDIR=bin
script:
  - go test
  - GOARCH=amd64 GOOS=linux go build -o $BINDIR/$NAME-linux
  - GOARCH=amd64 GOOS=darwin go build -o $BINDIR/$NAME-macos
  - chmod +x $BINDIR/$NAME-*
  - gzip $BINDIR/$NAME-linux
  - gzip $BINDIR/$NAME-macos
deploy:
  provider: releases
  prerelease: true
  skip_cleanup: true
  api_key:
    secure: dp1tc1h0er7aaAZ1hY0Xk/cUKwB0ifsAjg6e0M/Ad5NC87oucP6ESNFkDu0e9rUS1yB826/VnVGzNE/Z5zdjXVzPft+g5v5oRxzI4BKLhf07t9s+x8Z+3sApTxdsC5BvcN9x+5yRbpDLQ3biDPxSFu86j7m2pkEWw6XYNZO3/5y+RZXX7zu+d4MzTLUaA2kWl7KQAP0tEJNuw9ACDhpkw7LYbU/8q3E76prOTeme5/AT6Gxj7XhKUNP27lazhhqBSWM14ybPANqojNLEfMFHN/Eu2phYO07MuLTd4zuOIuw9y65kgvTFcHRlORjwUhnviXyA69obQejjgDI1WDOtU4PqpFaSLrxWtKI6k5VNWHARYggDm/wKl0WG7F0Kgio1KiGGhDg2yrbseXr/zBNaDhBtTFh6XJffqqwmgby1PXB6PWwfvWXooJMaQiFZczLWeMBl8v6XbSN6jtMTh/PQlKai6BcDd4LM8GQ7VHpSeff4qXEU4Vpnadjgs8VDPOHng6/HV+wDs8q2LrlMbnxLWxbCjOMUB6w7YnSrwH9owzKSoUs/531I4tTCRQIgipJtTK2b881/8osVjdMGS1mDXhBWO+OM0LCAdORJz+kN4PIkXXvKLt6jX74k6z4M3swFaqqtlTduN2Yy/ErsjguQO1VZfHmcpNssmJXI5QB9sxA=
  file: bin/*
  file_glob: true
  on:
    repo: Dreamacro/clash
    branch: master
    tags: true
