name: alpha
on: [push]
jobs:
  Build:
    if: ${{ !contains(github.event.head_commit.message, '[Skip CI]') }}
    runs-on: ubuntu-latest
    steps:
      - name: Get latest go version
        id: version
        run: |
          echo ::set-output name=go_version::$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g')
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.version.outputs.go_version }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Cache go module
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      #      - name: Get dependencies, run test
      #        run: |
      #          go test ./...
      - name: Build
        if: success()
        env:
          NAME: Clash.Meta
          BINDIR: bin
        run: make -j releases

      - name: Delete current release assets
        uses: andreaswilli/delete-release-assets-action@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: alpha
          deleteOnlyFromDrafts: false

      - name: Tag Repo
        uses: richardsimko/update-tag@v1
        with:
          tag_name: alpha
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Alpha
        uses: softprops/action-gh-release@v1
        if: ${{ env.GIT_BRANCH != 'Meta' && success() }}
        with:
          tag: ${{ github.ref }}
          tag_name: alpha
          files: bin/*
          prerelease: true

#      - name: send telegram message on push
#        uses: appleboy/telegram-action@master
#        with:
#          to: ${{ secrets.TTELEGRAM_CHAT_ID }}
#          token: ${{ secrets.TELEGRAM_TOKEN }}
#          message: |
#            ${{ github.actor }} created commit:
#            Commit message: ${{ github.event.commits[0].message }}
#
#            Repository: ${{ github.repository }}
#
#            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}