name: Mod Tidier
on:
  pull_request:
    branches:
      - Alpha
      - rm-iptables

jobs:
  mod_tidier:
    runs-on: ubuntu-latest
    name: Clean up mismatched go.sum files
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - uses: actions/setup-go@v2
      with:
        go-version: '1.19'
    - uses: evantorrie/mott-the-tidier@v1-beta
      with:
        gomods: |
          **/go.mod
          -tools/go.mod
        gosum_only: false
        gomodsum_only: true
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: auto-fix go.sum discrepancies